spring:
  application:
    name: sunshine-framework-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 开启健康检查
    healthcheck:
      enabled: true
  instance:
    # 服务续约调用任务的时间间隔 默认时间位30秒
    lease-renewal-interval-in-seconds: 20
    # 服务失效时间 默认时间位90秒
    lease-expiration-duration-in-seconds: 60
    # 获取服务调用的清单 默认时间位30秒
    registry-fetch-interval-seconds: 20
