server:
  port: 8663
eureka:
  client:
    # 开启健康检查
    # 不能写在bootstrap.yml中，官方的解释是
    # eureka.client.healthcheck.enabled=true should only be set in application.yml. 
    # Setting the value in bootstrap.yml causes undesirable side effects, such as registering in Eureka with an UNKNOWN status.
    healthcheck:
      enabled: true
logging:
  level:
    com.netflix: DEBUG
spring:
  cloud:
    gateway:
      routes:
      - id: hystrix_route
        #使用loadbalance
        uri: lb://sunshine-framework-manage:8088
        predicates:
        - Path=/sunshine-framework-manage
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
