server:
  port: 8663
eureka:
  client:
    # 开启健康检查
    # 不能写在bootstrap.yml中，官方的解释是
    # eureka.client.healthcheck.enabled=true should only be set in application.yml. 
    # Setting the value in bootstrap.yml causes undesirable side effects, such as registering in Eureka with an UNKNOWN status.
    healthcheck:
      enabled: true
management:
  server:
    # actuator端口 
    port: 9001
    endpoints:
      web:
        # 修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改  
        # base-path: /monitor
        # 开放所有页面节点  默认只开启了health、info两个节点
        exposure:
          include: *
      #显示健康具体信息  默认不会显示详细信息  
      health:
        show-details: always
logging:
  level:
    com.netflix: DEBUG
